requires 'perl' => '5.10.1';

requires 'boolean' => '>= 0.3.0';
requires 'AnyEvent';
requires 'AnyEvent::HTTP';
requires 'Class::Method::Modifiers';
requires 'Data::Path';
requires 'Data::Section::Simple';
requires 'DateTime::Format::HTTP';
requires 'DateTime::Format::Pg';
requires 'DateTime::Format::Strptime';
requires 'DBI';
requires 'DBD::Pg';
requires 'Exporter::Lite';
requires 'File::Basename';
requires 'File::Copy';
requires 'File::Path';
requires 'File::ShareDir';
requires 'File::Spec';
requires 'File::Temp';
requires 'FormValidator::Lite';
requires 'HTML::FillInForm::Lite';
requires 'HTTP::Session';
requires 'HTTP::Session::Store::DBI';
requires 'JSON';
requires 'Log::Dispatch';
requires 'LWP::UserAgent';
requires 'LWP::Protocol::https';
requires 'Module::Find';
requires 'Net::OAuth';
requires 'Plack';
requires 'Plack::Handler::CLI';
requires 'Router::Simple';
requires 'Scalar::Util';
requires 'Starman';
requires 'String::CamelCase';
requires 'Teng' => '>= 0.2.0';
requires 'Text::Xslate';
requires 'UNIVERSAL::require';
requires 'XML::Simple';